set(SINDRECPP_THIRD_AI_ONNXRUNTIME_MIN_VERSION
    "1.22" CACHE STRING "Minimum ONNX Runtime SDK version")
set(SINDRECPP_THIRD_AI_TENSORRT_MIN_VERSION
    "10.11" CACHE STRING "Minimum TensorRT SDK version")
set(SINDRECPP_THIRD_AI_CUDA_MIN_VERSION
    "12" CACHE STRING "Minimum CUDA Toolkit major version")
