include_guard(GLOBAL)

set(SINDRE_THIRD_GENERAL_PLATFORM "windows")
set(SINDRE_THIRD_GENERAL_PACKAGE_PROFILE "general-x64-windows-static")
set(SINDRE_THIRD_GENERAL_PACKAGE_TRIPLET "x64-windows-static")

set(SINDRE_THIRD_GENERAL_PACKAGE_ROOT
    "${SINDRE_THIRD_GENERAL_PACKAGE_CACHE_ROOT}/${SINDRE_THIRD_GENERAL_PACKAGE_PROFILE}/installed/${SINDRE_THIRD_GENERAL_PACKAGE_TRIPLET}")
set(SINDRE_GENERAL_PACKAGE_ROOT "${SINDRE_THIRD_GENERAL_PACKAGE_ROOT}")
if(NOT IS_DIRECTORY "${SINDRE_THIRD_GENERAL_PACKAGE_ROOT}/share")
    message(FATAL_ERROR
        "Fixed General Windows dependency profile is missing: ${SINDRE_THIRD_GENERAL_PACKAGE_ROOT}")
endif()
